### ISSUE TITLE
Documentation should have details about prerequisites

### ISSUE THREAD

**Issue by spnraju** [karriereat/vue-cli-plugin-e2e-nightwatch-cucumber#4]
Hi there! This seems to be a quite an interesting one. I was trying to run the test using `vue-cli-service test:e2e "tests/features"` But was getting the error 
>vue-cli-service : The term 'vue-cli-service' is not recognized as the name of a cmdlet, function, script  >file, or operable program.
 >Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
 >At line:1 char:1
 >+ vue-cli-service test:e2e "tests/features"
 >+ ~~~~~~~~~~~~~~~
 >  + CategoryInfo          : ObjectNotFound: (vue-cli-service:String) [], CommandNotFoundException
 >  + FullyQualifiedErrorId : CommandNotFoundException

Does it require anything other than nodejs and npmjs. Installed the packages using npm.

**Comment by Lorti** [comment]
Hi @spnraju,
there are no prerequesites other than using Vue CLI 3 and adding the plugin. When you run `vue add e2e-nightwatch-cucumber` the generator should add a script to your package.json you can run:
```diff
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint",
+    "test:e2e": "vue-cli-service test:e2e"
  },
```
