### ISSUE TITLE
Update to Nightwatch 1.0.18

### ISSUE THREAD

**Issue by hectorj** [karriereat/vue-cli-plugin-e2e-nightwatch-cucumber#7]
Hi!

Just wanted to know if there was a particular reason for pinning the nightwatch package to 1.0.6?

I'm having this issue https://github.com/nightwatchjs/nightwatch/issues/1847#issuecomment-405508878 and it seems to be fixed in 1.0.8

**Comment by Lorti** [comment]
Hey @hectorj,
the package is pinned to a specific version because I expected breaking changes in Nightwatch (and Nightwatch API) when I started the plugin. 
I’ll update the plugin with the newest versions and will get back to you. If you want you can also open up a pull request yourself.

**Comment by Lorti** [comment]
Can you please test vue-cli-plugin-e2e-nightwatch-cucumber@1.1.0?
